Diane Abbott	Lab
Gerry Adams	SF
Adam Afriyie	Con
Nick Ainger	Lab
Bob Ainsworth	Lab
Peter Ainsworth	Con
Danny Alexander	LDem
Douglas Alexander	Lab
Graham Allen	Lab
David Amess	Con
Michael Ancram	Con
David Anderson	Lab
Janet Anderson	Lab
James Arbuthnot	Con
Hilary Armstrong	Lab
Charlotte Atkins	Lab
Peter Atkinson	Con
Ian Austin	Lab
John Austin	Lab
Richard Bacon	Con
Adrian Bailey	Lab
William Bain	Lab
Vera Baird	Lab
Norman Baker	LDem
Tony Baldry	Con
Edward Balls	Lab
Gordon Banks	Lab
Gregory Barker	Con
Celia Barlow	Lab
John Baron	Con
John Barrett	LDem
Kevin Barron	Lab
John Battle	Lab
Hugh Bayley	Lab
Margaret Beckett	Lab
Anne Begg	Lab
Alan Beith	LDem
Stuart Bell	Lab
Henry Bellingham	Con
Hilary Benn	Lab
Joe Benton	Lab
Richard Benyon	Con
John Bercow	-
Paul Beresford	Con
Roger Berry	Lab
Clive Betts	Lab
Brian Binley	Con
Liz Blackman	Lab
Roberta Blackman-Woods	Lab
Hazel Blears	Lab
Bob Blizzard	Lab
David Blunkett	Lab
Crispin Blunt	Con
Peter Bone	Con
David Borrow	Lab
Tim Boswell	Con
Peter Bottomley	Con
Ben Bradshaw	Lab
Graham Brady	Con
Tom Brake	LDem
Julian Brazier	Con
Colin Breed	LDem
Kevin Brennan	Lab
James Brokenshire	Con
Annette Brooke	LDem
Gordon Brown	Lab
Lyn Brown	Lab
Nick Brown	Lab
Russell Brown	Lab
Des Browne	Lab
Jeremy Browne	LDem
Angela Browning	Con
Malcolm Bruce	LDem
Chris Bryant	Lab
Karen Buck	Lab
Richard Burden	Lab
Colin Burgon	Lab
Andy Burnham	Lab
Simon Burns	Con
David Burrowes	Con
Paul Burstow	LDem
Alistair Burt	Con
Lorely Burt	LDem
Dawn Butler	Lab
John Butterfil	Con
Stephen Byers	Lab
Liam Byrne	Lab
Vincent Cable	LDem
Richard Caborn	Lab
David Cairns	Lab
David Cameron	Con
Alan Campbell	Lab
Gregory Campbell	DUP
Menzies Campbell	LDem
Ronnie Campbell	Lab
Alistair Carmichael	LDem
Douglas Carswell	Con
William Cash	Con
Martin Caton	Lab
Ian Cawsey	Lab
Colin Challen	Lab
Ben Chapma	Lab
David Chayto	Lab
Christopher Chope	Con
Michael Clapham	Lab
James Clappison	Con
Greg Clark	Con
Charles Clarke	Lab
Kenneth Clarke	Con
Tom Clarke	Lab
Nicholas Clegg	LDem
David Clellan	Lab
Geoffrey Clifton-Brown	Con
Ann Clwyd	Lab
Vernon Coaker	Lab
Ann Coffey	Lab
Harry Cohen	Lab
Michael Connarty	Lab
Derek Conway	Ind
Frank Cook	Lab
Rosie Cooper	Lab
Yvette Cooper	Lab
Jeremy Corbyn	Lab
Patrick Cormack	Con
Jim Cousins	Lab
Geoffrey Cox	Con
Stephen Crabb	Con
David Crausby	Lab
Mary Creagh	Lab
Jon Cruddas	Lab
Ann Cryer	Lab
John Cummings	Lab
Jim Cunningham	Lab
Tony Cunningham	Lab
David Curry	Con
Claire Curtis-Thomas	Lab
Alistair Darling	Lab
Edward Davey	LDem
Wayne David	Lab
Ian Davidson	Lab
Dai Davies	Ind
David Davies	Con
Philip Davies	Con
Quentin Davies	Lab
David Davis	Con
Janet Dean	Lab
John Denham	Lab
Jim Devine	Lab
Parmjit Dhanda	Lab
Andrew Dismore	Lab
Jim Dobbin	Lab
Frank Dobson	Lab
Nigel Dodds	DUP
Pat Doherty	SF
Jeffrey M Donaldson	DUP
Brian H Donohoe	Lab
Frank Doran	Lab
Stephen Dorrell	Con
Nadine Dorries	Con
Jim Dowd	Lab
David Drew	Lab
James Duddridge	Con
Alan Duncan	Con
Iain Duncan Smith	Con
Philip Dunne	Con
Mark Durkan	SDLP
Angela Eagle	Lab
Maria Eagle	Lab
Clive Efford	Lab
Louise Ellman	Lab
Tobias Ellwood	Con
Natascha Engel	Lab
Jeff Ennis	Lab
Bill Etherington	Lab
Nigel Evans	Con
David Evennett	Con
Michael Fabricant	Con
Michael Fallon	Con
Paul Farrelly	Lab
Tim Farron	LDem
Lynne Featherstone	LDem
Frank Field	Lab
Mark Field	Con
Mark Fisher	Lab
Jim Fitzpatrick	Lab
Robert Flello	Lab
Caroline Flint	Lab
Paul Flynn	Lab
Barbara Follett	Lab
Don Foster	LDem
Michael Foster	Lab
Michael Jabez Foster	Lab
Liam Fox	Con
Hywel Francis	Lab
George Galloway	Res
Mike Gapes	Lab
Barry Gardiner	Lab
Edward Garnier	Con
David Gauke	Con
Andrew George	LDem
Bruce George	Lab
Neil Gerrard	Lab
Nick Gibb	Con
Sandra Gidley	LDem
Michelle Gildernew	SF
Cheryl Gillan	Con
Linda Gilroy	Lab
Roger Godsiff	Lab
Paul Goggins	Lab
Julia Goldsworthy	LDem
Helen Goodman	Lab
Paul Goodman	Con
Robert Goodwill	Con
Michael Gove	Con
James Gray	Con
Chris Grayling	Con
Damian Green	Con
Justine Greening	Con
John Greenway	Con
Dominic Grieve	Con
Nia Griffith	Lab
Nigel Griffiths	Lab
John Grogan	Lab
John Gumme	Con
Andrew Gwynne	Lab
William Hague	Con
Peter Hain	Lab
Mike Hall	Lab
Patrick Hall	Lab
David Hamilton	Lab
Fabian Hamilton	Lab
Philip Hammond	Con
Stephen Hammond	Con
Mike Hancock	LDem
Greg Hands	Con
David Hanson	Lab
Harriet Harman	Lab
Mark Harper	Con
Evan Harris	LDem
Alan Haselhurst	-
Dai Havard	Lab
John Hayes	Con
Sylvia Heal	-
Oliver Heald	Con
John Healey	Lab
David Heath	LDem
David Heathcoat-Amory	Con
John Hemming	LDem
Doug Henderson	Lab
Mark Hendrick	Lab
Charles Hendry	Con
Stephen Hepburn	Lab
John Heppell	Lab
Nick Herbert	Con
Lady Hermon	UUP
Stephen Hesford	Lab
Patricia Hewitt	Lab
David Heyes	Lab
Keith Hill	Lab
Meg Hillier	Lab
Mark Hoban	Con
Margaret Hodge	Lab
Sharon Hodgson	Lab
Kate Hoey	Lab
Douglas Hog	Con
Philip Hollobone	Con
Adam Holloway	Con
Paul Holmes	LDem
Jimmy Hood	Lab
Geoff Hoon	Lab
Phil Hope	Lab
Kelvin Hopkins	Lab
John Horam	Con
Martin Horwood	LDem
Stewart Hosie	SNP
Michael Howard	Con
David Howarth	LDem
Gerald Howarth	Con
John Howell	Con
Kim Howells	Lab
Lindsay Hoyle	Lab
Beverley Hughes	Lab
Simon Hughes	LDem
Christopher Huhne	LDem
Joan Humble	Lab
Jeremy Hunt	Con
Mark Hunter	LDem
Nick Hurd	Con
John Hutton	Lab
Brian Iddon	Lab
Eric Illsley	Lab
Adam Ingra	Lab
Huw Irranca-Davies	Lab
Michael Jack	Con
Glenda Jackson	Lab
Stewart Jackson	Con
Siân James	Lab
Bernard Jenkin	Con
Brian Jenkins	Lab
Alan Johnson	Lab
Diana Johnson	Lab
David Jones	Con
Helen Jones	Lab
Kevan Jones	Lab
Lynne Jones	Lab
Martyn Jones	Lab
Tessa Jowell	Lab
Eric Joyce	Lab
Gerald Kaufman	Lab
Daniel Kawczynski	Con
Sally Keeble	Lab
Barbara Keeley	Lab
Alan Keen	Lab
Ann Keen	Lab
Paul Keetch	LDem
Ruth Kelly	Lown
Sadiq Khan	Lab
David Kidney	Lab
Peter Kilfoyle	Lab
Julie Kirkbrid	Con
Greg Knight	Con
Jim Knight	Lab
Susan Kramer	LDem
Stephen Ladyman	Lab
Eleanor Laing	Con
Jacqui Lait	Con
Norman Lamb	LDem
David Lammy	Lab
Mark Lancaster	Con
Andrew Lansley	Con
David Laws	LDem
Bob Laxton	Lab
Mark Lazarowicz	Lab
John Leech	LDem
Edward Leigh	Con
David Lepper	Lab
Oliver Letwin	Con
Tom Levitt	Lab
Ivan Lewis	Lab
Julian Lewis	Con
Ian Liddell-Grainger	Con
David Lidington	Con
Peter Lilley	Con
Martin Linton	Lab
Tony Lloyd	Lab
Elfyn Llwyd	PC
Michael Lord	-
Tim Loughton	Con
Andrew Love	Lab
Ian Lucas	Lab
Peter Luff	Con
Andrew MacKay	Con
Andrew MacKinlay	Lab
David Maclean	Con
Denis MacShane	Lab
Fiona Mactaggart	Lab
Khalid Mahmood	Lab
Anne Main	Con
Shahid Malik	Lab
Humfrey Malins	Con
Judy Mallaber	Lab
John Mann	Lab
John Maples	Con
Rob Marris	Lab
Gordon Marsden	Lab
Robert Marshall-Andrews	Lab
Eric Martlew	Lab
John Mason	SNP
Michael Mate	Con
Francis Maude	Con
Theresa May	Con
Thomas McAvoy	Lab
Stephen McCabe	Lab
Chris McCafferty	Lab
Kerry McCarthy	Lab
Sarah McCarthy-Fry	Lab
Ian McCartney	Lab
William McCrea	DUP
Siobhain McDonagh	Lab
Alasdair McDonnell	SDLP
John McDonnell	Lab
Patrick McFadden	Lab
John McFall	Lab
James McGovern	Lab
Eddie McGrady	SDLP
Martin McGuinness	SF
Anne McGuire	Lab
Anne McIntosh	Con
Shona McIsaac	Lab
Ann McKechin	Lab
Rosemary McKenna	Lab
Patrick McLoughlin	Con
Tony McNulty	Lab
Michael Meacher	Lab
Alan Meale	Lab
Patrick Mercer	Con
Gillian Merron	Lab
Alun Michael	Lab
Alan Milburn	Lab
David Miliband	Lab
Edward Miliband	Lab
Andrew Miller	Lab
Maria Miller	Con
Anne Milton	Con
Andrew Mitchell	Con
Austin Mitchell	Lab
Anne Moffat	Lab
Laura Moffatt	Lab
Chris Mole	Lab
Madeleine Moon	Lab
Michael Moore	LDem
Margaret Moran	Lab
Jessica Morden	Lab
Julie Morgan	Lab
Elliot Morley	Lab
Malcolm Mos	Con
Kali Mountford	Lab
George Mudie	Lab
Greg Mulholland	LDem
Chris Mullin	Lab
David Mundell	Con
Meg Munn	Lab
Conor Murphy	SF
Denis Murphy	Lab
Jim Murphy	Lab
Paul Murphy	Lab
Andrew Murrison	Con
Doug Naysmith	Lab
Bob Neill	Con
Brooks Newmark	Con
Dan Norris	Lab
Mike O'Brien	Lab
Stephen O'Brien	Con
Edward O'Hara	Lab
Mark Oaten	LDem
Bill Olner	Lab
Lembit Öpik	LDem
George Osborne	Con
Sandra Osborne	Lab
Rich Owen	Lab
James Paice	Con
Ian Paisley	DUP
Nick Palmer	Lab
Owen Paterson	Con
Ian Pearson	Lab
Andrew Pelling	Ind
Michael Penning	Con
John Penrose	Con
Eric Pickles	Con
James Plaskitt	Lab
Greg Pope	Lab
Stephen Pound	Lab
Bridget Prentice	Lab
Gordon Prentice	Lab
John Prescot	Lab
Adam Price	PC
Dawn Primarolo	Lab
Mark Prisk	Con
Mark Pritchard	Con
Gwyn Prosser	Lab
John Pugh	LDem
Ken Purchase	Lab
James Purnel	Lab
Bill Rammell	Lab
John Randall	Con
Nick Raynsford	Lab
John Redwood	Con
Andy Reed	Lab
Jamie Reed	Lab
Alan Reid	LDem
John Reid	Lab
Willie Rennie	LDem
Malcolm Rifkind	Con
Linda Riordan	Lab
Andrew Robathan	Con
Angus Robertson	SNP
Hugh Robertson	Con
John Robertson	Lab
Laurence Robertson	Con
Geoffrey Robinson	Lab
Peter Robinson	DUP
Daniel Rogerson	LDem
Terry Rooney	Lab
Lindsay Roy	Lab
Chris Ruane	Lab
Joan Ruddock	Lab
David Ruffley	Con
Bob Russell	LDem
Christine Russell	Lab
Joan Ryan	Lab
Alex Salmon	SNP
Martin Salter	Lab
Adrian Sanders	LDem
Mohammad Sarwar	Lab
Lee Scott	Con
Alison Seabeck	Lab
Andrew Selous	Con
Grant Shapps	Con
Virendra Sharma	Lab
Jonathan R Shaw	Lab
Barry Sheerman	Lab
Richard Shepherd	Con
Jim Sheridan	Lab
Clare Short	Ind Lab
Mark Simmonds	Con
Siôn Simon	Lab
Alan Simpson	Lab
David Simpson	DUP
Keith Simpson	Con
Marsha Singh	Lab
Dennis Skinner	Lab
Andrew Slaughter	Lab
Andrew Smith	Lab
Angela Smith	Lab
Angela Smith	Lab
Chloe Smith	Con
Geraldine Smith	Lab
Jacqui Smith	Lab
John Smith	Lab
Robert Smith	LDem
Anne Snelgrove	Lab
Nicholas Soames	Con
Peter Soulsby	Lab
Helen Southworth	Lab
John Spellar	Lab
Caroline Spelman	Con
Phyllis Starkey	Lab
Anthony Steen	Con
Ian Stewart	Lab
Howard Stoate	Lab
Gavin Strang	Lab
Jack Straw	Lab
Gary Streeter	Con
Graham Stringer	Lab
Gisela Stuart	Lab
Graham Stuart	Con
Andrew Stunell	LDem
Gerry Sutcliffe	Lab
Desmond Swayne	Con
Jo Swinson	LDem
Hugo Swire	Con
Robert Syms	Con
Mark Tami	Lab
Sir Peter Tapsell	Con
Dari Taylor	Lab
Ian Taylor	Con
Matthew Taylor	LDem
Richard Taylor	Ind
Sarah Teather	LDem
Gareth Thomas	Lab
Emily Thornberry	Lab
John Thurso	LDem
Stephen Timms	Lab
Edward Timpson	Con
Paddy Tippin	Lab
Mark Todd	Lab
Don Touhig	Lab
David Tredinnick	Con
Jon Trickett	Lab
Paul Truswell	Lab
Andrew Turner	Con
Desmond Turner	Lab
Kitty Ussher	Lab
Edward Vaizey	Con
Shailesh Vara	Con
Keith Vaz	Lab
Peter Viggers	Con
Theresa Villiers	Con
Rudi Vis	Lab
Charles Walker	Con
Ben Wallace	Con
Joan Walley	Lab
Robert Walter	Con
Lynda Waltho	Lab
Claire Ward	Lab
Robert Wareing	Ind
Nigel Waterson	Con
Angela Watkinson	Con
Tom Watson	Lab
Dave Watts	Lab
Steve Webb	LDem
Michael Weir	SNP
Alan Whitehead	Lab
John Whittingdale	Con
Malcolm Wicks	Lab
Ann Widdecombe	Con
Bill Wiggin	Con
David Willetts	Con
Alan Williams	Lab
Betty Williams	Lab
Hywel Williams	PC
Mark Williams	LDem
Roger Williams	LDem
Stephen Williams	LDem
Phil Willis	LDem
Jennifer Willott	LDem
Michael Wills	Lab
David Wilshir	Con
Phil Wilson	Lab
Robert Wilson	Con
Sammy Wilson	DUP
David Winnick	Lab
Ann Winterton	Con
Rosie Winterton	Lab
Pete Wishart	SNP
Mike Wood	Lab
Shaun Woodward	Lab
Phil Woolas	Lab
Anthony D Wright	Lab
David Wright	Lab
Iain Wright	Lab
Jeremy Wright	Con
Tony Wright	Lab
Derek Wyatt	Lab
George Young	Con
Richard Younger-Ross	LDem
